In [1]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split

In [2]:
df = pd.read_csv("diabetes.csv")
df

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6   
1              1       85             66             29        0  26.6   
2              8      183             64              0        0  23.3   
3              1       89             66             23       94  28.1   
4              0      137             40             35      168  43.1   
..           ...      ...            ...            ...      ...   ...   
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  Outcome  
0                       0.627   50        1  
1                       0.351   31        0  
2                       0.672   32        1  
3                       0.167   21        0  
4                       2.288   33        1  
..                        ...  ...      ...  
763                     0.171   63        0  
764                     0.340   27        0  
765                     0.245   30        0  
766                     0.349   47        1  
767                     0.315   23        0  

[768 rows x 9 columns]

In [3]:
print(df.shape)

(768, 9)


In [4]:
print(df.isna().sum())

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64


In [5]:
print(df['Outcome'].value_counts())

0    500
1    268
Name: Outcome, dtype: int64


In [6]:
X =  df.drop(['Outcome'], axis = 1)
y = df['Outcome']

In [7]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_st = scaler.fit_transform(X)
X_st

# X- вектор признаков исходного набора 
# X_st - 

array([[ 0.63994726,  0.84832379,  0.14964075, ...,  0.20401277,
         0.46849198,  1.4259954 ],
       [-0.84488505, -1.12339636, -0.16054575, ..., -0.68442195,
        -0.36506078, -0.19067191],
       [ 1.23388019,  1.94372388, -0.26394125, ..., -1.10325546,
         0.60439732, -0.10558415],
       ...,
       [ 0.3429808 ,  0.00330087,  0.14964075, ..., -0.73518964,
        -0.68519336, -0.27575966],
       [-0.84488505,  0.1597866 , -0.47073225, ..., -0.24020459,
        -0.37110101,  1.17073215],
       [-0.84488505, -0.8730192 ,  0.04624525, ..., -0.20212881,
        -0.47378505, -0.87137393]])

In [8]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
X_norm = scaler.fit_transform(X)
X_norm

array([[0.35294118, 0.74371859, 0.59016393, ..., 0.50074516, 0.23441503,
        0.48333333],
       [0.05882353, 0.42713568, 0.54098361, ..., 0.39642325, 0.11656704,
        0.16666667],
       [0.47058824, 0.91959799, 0.52459016, ..., 0.34724292, 0.25362938,
        0.18333333],
       ...,
       [0.29411765, 0.6080402 , 0.59016393, ..., 0.390462  , 0.07130658,
        0.15      ],
       [0.05882353, 0.63316583, 0.49180328, ..., 0.4485842 , 0.11571307,
        0.43333333],
       [0.05882353, 0.46733668, 0.57377049, ..., 0.45305514, 0.10119556,
        0.03333333]])

In [9]:


X_train, X_test, y_train, y_test = train_test_split(X_st, y, test_size=0.3, random_state = 42)



In [10]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix

scores = []
for i in range(1,15):

  knn = KNeighborsClassifier(i)
  knn.fit(X_train, y_train)
  answers = knn.predict(X_test)

  scores.append(knn.score(X_test, y_test))

print(scores)

  

[0.6233766233766234, 0.670995670995671, 0.70995670995671, 0.6926406926406926, 0.6926406926406926, 0.6883116883116883, 0.7186147186147186, 0.683982683982684, 0.7012987012987013, 0.6926406926406926, 0.7012987012987013, 0.7142857142857143, 0.7142857142857143, 0.7186147186147186]


In [11]:
max_score = max(scores)
scores_ind = [i for i, v in enumerate(scores) if v == max_score]
scores_ind

[6, 13]

In [12]:
knn = KNeighborsClassifier(5)

knn.fit(X_train, y_train)

y_pred = knn.predict(X_test)

confusion_matrix(y_test, y_pred)

array([[119,  32],
       [ 39,  41]], dtype=int64)

In [13]:
from sklearn.metrics import accuracy_score
from sklearn.metrics import recall_score
from sklearn.metrics import precision_score

print("Accuracy" , accuracy_score(y_test, y_pred))
print("Recall" ,recall_score(y_test, y_pred))
print("Precision" , precision_score(y_test, y_pred))

Accuracy 0.6926406926406926
Recall 0.5125
Precision 0.5616438356164384


In [14]:
X_train, X_test, y_train, y_test = train_test_split(X_norm, y, test_size=0.3, random_state = 42)

In [15]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix

scores = []
for i in range(1,15):

  knn = KNeighborsClassifier(i)
  knn.fit(X_train, y_train)
  answers = knn.predict(X_test)

  scores.append(knn.score(X_test, y_test))

print(scores)

[0.6753246753246753, 0.6796536796536796, 0.6926406926406926, 0.696969696969697, 0.6796536796536796, 0.6666666666666666, 0.7142857142857143, 0.696969696969697, 0.7229437229437229, 0.7056277056277056, 0.7012987012987013, 0.6883116883116883, 0.6926406926406926, 0.6883116883116883]


In [16]:
max_score = max(scores)
scores_ind = [i for i, v in enumerate(scores) if v == max_score]
scores_ind

[8]

In [17]:
knn = KNeighborsClassifier(5)

knn.fit(X_train, y_train)

y_pred = knn.predict(X_test)

confusion_matrix(y_test, y_pred)

array([[118,  33],
       [ 41,  39]], dtype=int64)

In [18]:
from sklearn.metrics import accuracy_score
from sklearn.metrics import recall_score
from sklearn.metrics import precision_score

print("Accuracy" , accuracy_score(y_test, y_pred))
print("Recall" ,recall_score(y_test, y_pred))
print("Precision" , precision_score(y_test, y_pred))

Accuracy 0.6796536796536796
Recall 0.4875
Precision 0.5416666666666666


In [ ]:
#модель работает лучше на стандрартизированных данных, так как точность модели выше, чем у нормализованных( у стандартизированной 69, а у нормализованной 67)

In [33]:
from sklearn.linear_model import LogisticRegression


In [34]:
X =  df.drop(['Outcome'], axis = 1)
y = df['Outcome']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state = 42)


In [35]:
model = LogisticRegression()
# модель учится, для этого ей нужны правильные
model.fit(X_train, y_train)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [36]:
answers_pred = model.predict(X_test)
# answers_pred - ответы которые вернула модель для X_test
# y_test - это правильные ответы для X_test
print(model.score(X_test, y_test))

0.7402597402597403


In [37]:
print("Accuracy" , accuracy_score(y_test, y_pred))
print("Recall" ,recall_score(y_test, y_pred))
print("Precision" , precision_score(y_test, y_pred))

Accuracy 0.6796536796536796
Recall 0.4875
Precision 0.5416666666666666
