In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving diabetes.csv to diabetes.csv


In [ ]:
df = pd.read_csv("diabetes.csv")
df

Pregnancies  Glucose  ...  Age  Outcome
0              6      148  ...   50        1
1              1       85  ...   31        0
2              8      183  ...   32        1
3              1       89  ...   21        0
4              0      137  ...   33        1
..           ...      ...  ...  ...      ...
763           10      101  ...   63        0
764            2      122  ...   27        0
765            5      121  ...   30        0
766            1      126  ...   47        1
767            1       93  ...   23        0

[768 rows x 9 columns]

In [ ]:
X = df.drop(['Outcome'], axis = 1)
y = df['Outcome']

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

tree = DecisionTreeClassifier()

tree.fit(X_train, y_train)
y_pred_tree = tree.predict(X_test)

In [ ]:
from sklearn.metrics import accuracy_score
from sklearn.metrics import recall_score
from sklearn.metrics import precision_score

print("Accuracy:", accuracy_score(y_test, y_pred_tree))
print("Recall:", recall_score(y_test, y_pred_tree))
print("Precision:", precision_score(y_test, y_pred_tree))

Accuracy: 0.6926406926406926
Recall: 0.675
Precision: 0.5454545454545454


In [ ]:
kf = KFold(n_splits=5)

tree = DecisionTreeClassifier(criterion='gini', max_depth=4, random_state=1)

cvs = cross_val_score(estimator=tree, X=X, y=y, cv=kf, scoring='accuracy')

print(cvs)
print(cvs.mean())

[0.73376623 0.65584416 0.78571429 0.82352941 0.7254902 ]
0.7448688566335624


In [ ]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
X_norm = scaler.fit_transform(X)
X_norm

array([[0.35294118, 0.74371859, 0.59016393, ..., 0.50074516, 0.23441503,
        0.48333333],
       [0.05882353, 0.42713568, 0.54098361, ..., 0.39642325, 0.11656704,
        0.16666667],
       [0.47058824, 0.91959799, 0.52459016, ..., 0.34724292, 0.25362938,
        0.18333333],
       ...,
       [0.29411765, 0.6080402 , 0.59016393, ..., 0.390462  , 0.07130658,
        0.15      ],
       [0.05882353, 0.63316583, 0.49180328, ..., 0.4485842 , 0.11571307,
        0.43333333],
       [0.05882353, 0.46733668, 0.57377049, ..., 0.45305514, 0.10119556,
        0.03333333]])

In [ ]:
X_train,X_test,y_train,y_test = train_test_split(X_norm, y, test_size=1/3, random_state=42)

tree = DecisionTreeClassifier(criterion='gini', max_depth=4, random_state=42)

tree.fit(X_train, y_train)
y_pred_tree = tree.predict(X_test)

In [ ]:
print('accuracy:', accuracy_score(y_test, y_pred))
print('recall:', recall_score(y_test, y_pred))
print('precision:', precision_score(y_test, y_pred))

accuracy: 0.6875
recall: 0.5
precision: 0.5375


In [ ]:
kf = KFold(n_splits=5)
 
tree = DecisionTreeClassifier(criterion='gini', max_depth=4, random_state=42)

cvs = cross_val_score(estimator=tree, X=X, y=y, cv=kf, scoring='accuracy')

print(cvs)
print(cvs.mean())

[0.72727273 0.65584416 0.78571429 0.81699346 0.7254902 ]
0.7422629657923776


In [ ]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_st = scaler.fit_transform(X)
X_st

array([[ 0.63994726,  0.84832379,  0.14964075, ...,  0.20401277,
         0.46849198,  1.4259954 ],
       [-0.84488505, -1.12339636, -0.16054575, ..., -0.68442195,
        -0.36506078, -0.19067191],
       [ 1.23388019,  1.94372388, -0.26394125, ..., -1.10325546,
         0.60439732, -0.10558415],
       ...,
       [ 0.3429808 ,  0.00330087,  0.14964075, ..., -0.73518964,
        -0.68519336, -0.27575966],
       [-0.84488505,  0.1597866 , -0.47073225, ..., -0.24020459,
        -0.37110101,  1.17073215],
       [-0.84488505, -0.8730192 ,  0.04624525, ..., -0.20212881,
        -0.47378505, -0.87137393]])

In [ ]:
X_train,X_test,y_train,y_test = train_test_split(X_st, y, test_size=1/3, random_state=42)

tree = DecisionTreeClassifier(criterion='gini', max_depth=4, random_state=42)

tree.fit(X_train, y_train)
y_pred_tree = tree.predict(X_test)

In [ ]:
print('accuracy:', accuracy_score(y_test, y_pred))
print('recall:', recall_score(y_test, y_pred))
print('precision:', precision_score(y_test, y_pred))

accuracy: 0.6875
recall: 0.5
precision: 0.5375


In [ ]:
kf = KFold(n_splits=5)

tree = DecisionTreeClassifier(criterion='gini', max_depth=1, random_state=42)

cvs = cross_val_score(estimator=tree, X=X, y=y, cv=kf, scoring='accuracy')

print(cvs)
print(cvs.mean()) 

[0.68181818 0.68831169 0.75974026 0.77777778 0.74509804]
0.7305491893727187


In [ ]:
scaler = StandardScaler()
X_st = scaler.fit_transform(X)
X_st


X_train, X_test, y_train, y_test = train_test_split(X_st, y, test_size = 1/3)
tree = DecisionTreeClassifier()

tree.fit(X_train, y_train)
y_pred_tree = tree.predict(X_test)

In [ ]:
print("Accuracy:", accuracy_score(y_test, y_pred_tree))
print("Recall:", recall_score(y_test, y_pred_tree))
print("Precision:", precision_score(y_test, y_pred_tree))

Accuracy: 0.734375
Recall: 0.6136363636363636
Precision: 0.6136363636363636


In [ ]:
kf = KFold(n_splits=5)
tree = DecisionTreeClassifier(criterion = 'entropy', splitter = 'random')

cvs = cross_val_score(estimator=tree, X=X, y=y, cv=kf, scoring='accuracy')
print(cvs)
print(cvs.mean())

[0.69480519 0.66233766 0.74025974 0.7254902  0.69281046]
0.7031406501994738


In [ ]:
scaler = StandardScaler()
X_st = scaler.fit_transform(X)
X_st


X_train, X_test, y_train, y_test = train_test_split(X_st, y, test_size = 1/3)
tree = DecisionTreeClassifier()

tree.fit(X_train, y_train)
y_pred_tree = tree.predict(X_test)

In [ ]:
print("Accuracy:", accuracy_score(y_test, y_pred_tree))
print("Recall:", recall_score(y_test, y_pred_tree))
print("Precision:", precision_score(y_test, y_pred_tree))

Accuracy: 0.640625
Recall: 0.4479166666666667
Precision: 0.524390243902439


In [ ]:
lg = LogisticRegression()
cvs = cross_val_score(estimator=tree, X=X, y=y, cv=kf, scoring='accuracy')
print(cvs)
print(cvs.mean())

[0.67532468 0.61038961 0.73376623 0.80392157 0.7254902 ]
0.7097784568372804


In [ ]:
scaler = StandardScaler()
X_st = scaler.fit_transform(X)
X_st


X_train, X_test, y_train, y_test = train_test_split(X_st, y, test_size = 1/3)
tree = DecisionTreeClassifier()

tree.fit(X_train, y_train)
y_pred_tree = tree.predict(X_test)

In [ ]:
print("Accuracy:", accuracy_score(y_test, y_pred_tree))
print("Recall:", recall_score(y_test, y_pred_tree))
print("Precision:", precision_score(y_test, y_pred_tree))

Accuracy: 0.72265625
Recall: 0.5252525252525253
Precision: 0.6842105263157895


In [ ]:
knn = KNeighborsClassifier()
cvs = cross_val_score(estimator=tree, X=X, y=y, cv=kf, scoring='accuracy')
print(cvs)
print(cvs.mean())

[0.7012987  0.59090909 0.71428571 0.78431373 0.73202614]
0.7045666751549104


In [ ]:

scaler = StandardScaler()
X_st = scaler.fit_transform(X)
X_st


X_train, X_test, y_train, y_test = train_test_split(X_st, y, test_size = 1/3)
tree = DecisionTreeClassifier()

tree.fit(X_train, y_train)
y_pred_tree = tree.predict(X_test)


print("Accuracy:", accuracy_score(y_test, y_pred_tree))
print("Recall:", recall_score(y_test, y_pred_tree))
print("Precision:", precision_score(y_test, y_pred_tree))

Accuracy: 0.703125
Recall: 0.5842696629213483
Precision: 0.5714285714285714


In [ ]:
kf = KFold(n_splits=5)
lg = LogisticRegression()
cvs = cross_val_score(estimator=tree, X=X, y=y, cv=kf, scoring='accuracy')
print(cvs)
print(cvs.mean())

[0.71428571 0.61038961 0.71428571 0.80392157 0.73202614]
0.714981750275868


In [ ]:

scaler = StandardScaler()
X_st = scaler.fit_transform(X)
X_st


X_train, X_test, y_train, y_test = train_test_split(X_st, y, test_size = 1/3)
tree = DecisionTreeClassifier()

tree.fit(X_train, y_train)
y_pred_tree = tree.predict(X_test)


print("Accuracy:", accuracy_score(y_test, y_pred_tree))
print("Recall:", recall_score(y_test, y_pred_tree))
print("Precision:", precision_score(y_test, y_pred_tree))

Accuracy: 0.671875
Recall: 0.5567010309278351
Precision: 0.5684210526315789


In [ ]:
kf = KFold(n_splits=5)
knn = KNeighborsClassifier()
cvs = cross_val_score(estimator=tree, X=X, y=y, cv=kf, scoring='accuracy')
print(cvs)
print(cvs.mean())

[0.69480519 0.62337662 0.70779221 0.81045752 0.73856209]
0.7149987267634327
