In [15]:
import pandas as pd
import numpy as np
from sklearn.cluster import KMeans
from sklearn.datasets import make_blobs
from sklearn import datasets
import matplotlib.pyplot as plt
from sklearn.metrics import accuracy_score
from sklearn.metrics import recall_score
from sklearn.metrics import precision_score
import scipy.cluster.hierarchy as sch
from sklearn.cluster import AgglomerativeClustering
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score, f1_score
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import KFold



In [2]:
from google.colab import files
uploaded = files.upload()

Saving diabetes (1).csv to diabetes (1).csv


In [3]:
df = pd.read_csv("diabetes (1).csv")
df


Pregnancies  Glucose  ...  Age  Outcome
0              6      148  ...   50        1
1              1       85  ...   31        0
2              8      183  ...   32        1
3              1       89  ...   21        0
4              0      137  ...   33        1
..           ...      ...  ...  ...      ...
763           10      101  ...   63        0
764            2      122  ...   27        0
765            5      121  ...   30        0
766            1      126  ...   47        1
767            1       93  ...   23        0

[768 rows x 9 columns]

In [12]:
X = df.drop(['Outcome'], axis = 1)
y = df['Outcome']

In [28]:
# нормализовали
scaler = MinMaxScaler()
X_st = scaler.fit_transform(X)
X_st

array([[0.35294118, 0.74371859, 0.59016393, ..., 0.50074516, 0.23441503,
        0.48333333],
       [0.05882353, 0.42713568, 0.54098361, ..., 0.39642325, 0.11656704,
        0.16666667],
       [0.47058824, 0.91959799, 0.52459016, ..., 0.34724292, 0.25362938,
        0.18333333],
       ...,
       [0.29411765, 0.6080402 , 0.59016393, ..., 0.390462  , 0.07130658,
        0.15      ],
       [0.05882353, 0.63316583, 0.49180328, ..., 0.4485842 , 0.11571307,
        0.43333333],
       [0.05882353, 0.46733668, 0.57377049, ..., 0.45305514, 0.10119556,
        0.03333333]])

In [29]:
X_train, X_test, y_train, y_test = train_test_split(X_st, y, test_size = 1/3)
tree = DecisionTreeClassifier()

tree.fit(X_train, y_train)
y_pred_tree = tree.predict(X_test)

In [30]:
print("Accuracy:", accuracy_score(y_test, y_pred_tree))
print("Recall:", recall_score(y_test, y_pred_tree))
print("Precision:", precision_score(y_test, y_pred_tree))

Accuracy: 0.65625
Recall: 0.4897959183673469
Precision: 0.5581395348837209


In [31]:
kf = KFold(n_splits=5)
tree = DecisionTreeClassifier()

cvs = cross_val_score(estimator=tree, X=X, y=y, cv=kf, scoring='accuracy')

print(cvs)
print(cvs.mean())
# 1й пункт есть

[0.66883117 0.61038961 0.72077922 0.77124183 0.71895425]
0.6980392156862745


In [33]:
#стандартизируем
scaler = StandardScaler()
X_st = scaler.fit_transform(X)
X_st


X_train, X_test, y_train, y_test = train_test_split(X_st, y, test_size = 1/3)
tree = DecisionTreeClassifier()

tree.fit(X_train, y_train)
y_pred_tree = tree.predict(X_test)


print("Accuracy:", accuracy_score(y_test, y_pred_tree))
print("Recall:", recall_score(y_test, y_pred_tree))
print("Precision:", precision_score(y_test, y_pred_tree))


kf = KFold(n_splits=5)
tree = DecisionTreeClassifier()
cvs = cross_val_score(estimator=tree, X=X, y=y, cv=kf, scoring='accuracy')
print(cvs)
print(cvs.mean())
# 2й пункт есть (он лучше 1го по качеству)

Accuracy: 0.7265625
Recall: 0.6333333333333333
Precision: 0.6063829787234043
[0.69480519 0.61038961 0.72727273 0.80392157 0.73202614]
0.7136830489771666


In [88]:
#начало 3го пункта (взял 2й пункт, так как он лучше 1го, но поминял глубину)
scaler = StandardScaler()
X_st = scaler.fit_transform(X)
X_st


X_train, X_test, y_train, y_test = train_test_split(X_st, y, test_size = 1/3)
tree = DecisionTreeClassifier()

tree.fit(X_train, y_train)
y_pred_tree = tree.predict(X_test)


print("Accuracy:", accuracy_score(y_test, y_pred_tree))
print("Recall:", recall_score(y_test, y_pred_tree))
print("Precision:", precision_score(y_test, y_pred_tree))


kf = KFold(n_splits=5)
tree = DecisionTreeClassifier(criterion = 'entropy', splitter = 'random')
#улучшились все показатели модели

cvs = cross_val_score(estimator=tree, X=X, y=y, cv=kf, scoring='accuracy')
print(cvs)
print(cvs.mean())
#конец 3го пункта

Accuracy: 0.71875
Recall: 0.5054945054945055
Precision: 0.6301369863013698
[0.68831169 0.66883117 0.72077922 0.73202614 0.64052288]
0.6900942195059842


In [99]:
#4й пункт 
# без kFold логистическая и ближайшие соседи (везде беру стандатизированные, ибо почему бы и нет :3)
scaler = StandardScaler()
X_st = scaler.fit_transform(X)
X_st


X_train, X_test, y_train, y_test = train_test_split(X_st, y, test_size = 1/3)
tree = DecisionTreeClassifier()

tree.fit(X_train, y_train)
y_pred_tree = tree.predict(X_test)


print("Accuracy:", accuracy_score(y_test, y_pred_tree))
print("Recall:", recall_score(y_test, y_pred_tree))
print("Precision:", precision_score(y_test, y_pred_tree))

log = LogisticRegression()
cvs = cross_val_score(estimator=tree, X=X, y=y, cv=kf, scoring='accuracy')
print(cvs)
print(cvs.mean())
# конец логистической


Accuracy: 0.65234375
Recall: 0.5833333333333334
Precision: 0.47572815533980584
[0.68831169 0.61688312 0.74675325 0.80392157 0.7254902 ]
0.7162719633307869


In [98]:
scaler = StandardScaler()
X_st = scaler.fit_transform(X)
X_st


X_train, X_test, y_train, y_test = train_test_split(X_st, y, test_size = 1/3)
tree = DecisionTreeClassifier()

tree.fit(X_train, y_train)
y_pred_tree = tree.predict(X_test)


print("Accuracy:", accuracy_score(y_test, y_pred_tree))
print("Recall:", recall_score(y_test, y_pred_tree))
print("Precision:", precision_score(y_test, y_pred_tree))

knn = KNeighborsClassifier()
cvs = cross_val_score(estimator=tree, X=X, y=y, cv=kf, scoring='accuracy')
print(cvs)
print(cvs.mean())
#конец ближайших соседей

Accuracy: 0.69140625
Recall: 0.5113636363636364
Precision: 0.5555555555555556
[0.70779221 0.63636364 0.72077922 0.77777778 0.7254902 ]
0.7136406077582548


In [ ]:
#теперь тоже самое, но с KFold

In [104]:
scaler = StandardScaler()
X_st = scaler.fit_transform(X)
X_st


X_train, X_test, y_train, y_test = train_test_split(X_st, y, test_size = 1/3)
tree = DecisionTreeClassifier()

tree.fit(X_train, y_train)
y_pred_tree = tree.predict(X_test)


print("Accuracy:", accuracy_score(y_test, y_pred_tree))
print("Recall:", recall_score(y_test, y_pred_tree))
print("Precision:", precision_score(y_test, y_pred_tree))
kf = KFold(n_splits=5)
log = LogisticRegression()
cvs = cross_val_score(estimator=tree, X=X, y=y, cv=kf, scoring='accuracy')
print(cvs)
print(cvs.mean())
# конец логистической

Accuracy: 0.66796875
Recall: 0.5595238095238095
Precision: 0.49473684210526314
[0.68181818 0.62987013 0.73376623 0.78431373 0.73202614]
0.7123588829471182


In [106]:
scaler = StandardScaler()
X_st = scaler.fit_transform(X)
X_st


X_train, X_test, y_train, y_test = train_test_split(X_st, y, test_size = 1/3)
tree = DecisionTreeClassifier()

tree.fit(X_train, y_train)
y_pred_tree = tree.predict(X_test)


print("Accuracy:", accuracy_score(y_test, y_pred_tree))
print("Recall:", recall_score(y_test, y_pred_tree))
print("Precision:", precision_score(y_test, y_pred_tree))
kf = KFold(n_splits=5)
knn = KNeighborsClassifier()
cvs = cross_val_score(estimator=tree, X=X, y=y, cv=kf, scoring='accuracy')
print(cvs)
print(cvs.mean())
#конец ближайших соседей

Accuracy: 0.72265625
Recall: 0.5714285714285714
Precision: 0.49382716049382713
[0.69480519 0.62337662 0.73376623 0.77777778 0.73202614]
0.7123503947033358


In [ ]:
#осознаём, что kFold почти ничего не поменял((( , но зато внесение дополнительных параметров в функцию, всё таки улучшело качество модели