In [ ]:
# импортируем библиотеки
import pandas as pd
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import KFold
from sklearn.metrics import accuracy_score
from sklearn.metrics import recall_score
from sklearn.metrics import precision_score
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import confusion_matrix
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving winequality-red.csv to winequality-red (3).csv


In [ ]:
df = pd.read_csv("winequality-red.csv")
df

fixed acidity  volatile acidity  citric acid  ...  sulphates  alcohol  quality
0               7.4             0.700         0.00  ...       0.56      9.4        5
1               7.8             0.880         0.00  ...       0.68      9.8        5
2               7.8             0.760         0.04  ...       0.65      9.8        5
3              11.2             0.280         0.56  ...       0.58      9.8        6
4               7.4             0.700         0.00  ...       0.56      9.4        5
...             ...               ...          ...  ...        ...      ...      ...
1594            6.2             0.600         0.08  ...       0.58     10.5        5
1595            5.9             0.550         0.10  ...       0.76     11.2        6
1596            6.3             0.510         0.13  ...       0.75     11.0        6
1597            5.9             0.645         0.12  ...       0.71     10.2        5
1598            6.0             0.310         0.47  ...       0.66     11.0        6

[1599 rows x 12 columns]

In [337]:
print(df.shape) # размерность датафрейма
print('_________________________')
print(df.isna().sum()) # проверка на пустые значения
print('_________________________') # информация о данных
print(df.dtypes)

(1599, 12)
_________________________
fixed acidity           0
volatile acidity        0
citric acid             0
residual sugar          0
chlorides               0
free sulfur dioxide     0
total sulfur dioxide    0
density                 0
pH                      0
sulphates               0
alcohol                 0
quality                 0
dtype: int64
_________________________
fixed acidity           float64
volatile acidity        float64
citric acid             float64
residual sugar          float64
chlorides               float64
free sulfur dioxide     float64
total sulfur dioxide    float64
density                 float64
pH                      float64
sulphates               float64
alcohol                 float64
quality                   int64
dtype: object


In [ ]:
df['quality'].value_counts() # значения столбца quality

5    681
6    638
7    199
4     53
8     18
3     10
Name: quality, dtype: int64

In [ ]:
df.apply(pd.Series.round) # округление

fixed acidity  volatile acidity  citric acid  ...  sulphates  alcohol  quality
0               7.0               1.0          0.0  ...        1.0      9.0        5
1               8.0               1.0          0.0  ...        1.0     10.0        5
2               8.0               1.0          0.0  ...        1.0     10.0        5
3              11.0               0.0          1.0  ...        1.0     10.0        6
4               7.0               1.0          0.0  ...        1.0      9.0        5
...             ...               ...          ...  ...        ...      ...      ...
1594            6.0               1.0          0.0  ...        1.0     10.0        5
1595            6.0               1.0          0.0  ...        1.0     11.0        6
1596            6.0               1.0          0.0  ...        1.0     11.0        6
1597            6.0               1.0          0.0  ...        1.0     10.0        5
1598            6.0               0.0          0.0  ...        1.0     11.0        6

[1599 rows x 12 columns]

In [ ]:
df.columns

Index(['fixed acidity', 'volatile acidity', 'citric acid', 'residual sugar',
       'chlorides', 'free sulfur dioxide', 'total sulfur dioxide', 'density',
       'pH', 'sulphates', 'alcohol', 'quality'],
      dtype='object')

In [ ]:
X =  df.drop(['quality'], axis = 1) # выделяем вектор признаков X (X - вектор признаков исходного набора)
y = df['quality'] # выделяем вектор ответов y

In [ ]:
# MinMaxScaler - функция из библиотеки sklearn.preprocessing, которая позволяет нормализовать признаки
# X_st - вектор стандартизированных признаков
# Стандартизируем данные
scaler = StandardScaler()
X_st = scaler.fit_transform(X)
X_st

array([[-0.52835961,  0.96187667, -1.39147228, ...,  1.28864292,
        -0.57920652, -0.96024611],
       [-0.29854743,  1.96744245, -1.39147228, ..., -0.7199333 ,
         0.1289504 , -0.58477711],
       [-0.29854743,  1.29706527, -1.18607043, ..., -0.33117661,
        -0.04808883, -0.58477711],
       ...,
       [-1.1603431 , -0.09955388, -0.72391627, ...,  0.70550789,
         0.54204194,  0.54162988],
       [-1.39015528,  0.65462046, -0.77526673, ...,  1.6773996 ,
         0.30598963, -0.20930812],
       [-1.33270223, -1.21684919,  1.02199944, ...,  0.51112954,
         0.01092425,  0.54162988]])

In [ ]:
# StandardScaler - функция из библиотеки sklearn.preprocessing, которая позволяет стандартизировать признаки
# X_norm - вектор нормализованных признаков
# Нормализуем данные
scaler = MinMaxScaler()
X_norm = scaler.fit_transform(X)
X_norm

array([[0.24778761, 0.39726027, 0.        , ..., 0.60629921, 0.13772455,
        0.15384615],
       [0.28318584, 0.52054795, 0.        , ..., 0.36220472, 0.20958084,
        0.21538462],
       [0.28318584, 0.43835616, 0.04      , ..., 0.40944882, 0.19161677,
        0.21538462],
       ...,
       [0.15044248, 0.26712329, 0.13      , ..., 0.53543307, 0.25149701,
        0.4       ],
       [0.11504425, 0.35958904, 0.12      , ..., 0.65354331, 0.22754491,
        0.27692308],
       [0.12389381, 0.13013699, 0.47      , ..., 0.51181102, 0.19760479,
        0.4       ]])

In [ ]:
# Логистическая регрессия для нормализованных данных
X_train, X_test, y_train, y_test = train_test_split(X_norm,y, test_size=0.3, random_state = 42)
model = LogisticRegression()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)

print("Accuracy" , accuracy_score(y_test, y_pred))
print("Recall" ,recall_score(y_test, y_pred,average='macro'))
print("Precision" , precision_score(y_test, y_pred,average='macro'))

Accuracy 0.5541666666666667
Recall 0.23620113493064313
Precision 0.24523032133730804


/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [ ]:
# Логистическая регрессия с помощью кроссвалидации (нормализованные данные)
kf = KFold(n_splits = 5)

tree = DecisionTreeClassifier()

cvs = cross_val_score(estimator = model, X = X_norm, y = y, cv = kf, scoring = 'accuracy')

print(cvs)
print(cvs.mean())

[0.596875   0.528125   0.578125   0.54375    0.63009404]
0.5753938087774295


In [ ]:
# Логистическая регрессия для стандартизированных данных
X_train, X_test, y_train, y_test = train_test_split(X_st,y, test_size=0.3, random_state = 42)
model = LogisticRegression()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)

print("Accuracy" , accuracy_score(y_test, y_pred))
print("Recall" ,recall_score(y_test, y_pred,average='macro'))
print("Precision" , precision_score(y_test, y_pred,average='macro'))

Accuracy 0.5645833333333333
Recall 0.2593355051141936
Precision 0.2614832126054678


/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [ ]:
# Логистическая регрессия с помощью кроссвалидации (стандартизированные данные)
kf = KFold(n_splits = 5)

tree = DecisionTreeClassifier()

cvs = cross_val_score(estimator = model, X = X_st, y = y, cv = kf, scoring = 'accuracy')

print(cvs)
print(cvs.mean())

/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


[0.58125    0.528125   0.609375   0.565625   0.63009404]
0.5828938087774295


/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


In [ ]:
# Метод ближайших соседей для нормализованных  данных
X_train, X_test, y_train, y_test = train_test_split(X_norm, y, test_size=0.3, random_state = 42)

scores = []
for i in range(1,15):

  knn = KNeighborsClassifier(i)
  knn.fit(X_train, y_train)
  answers = knn.predict(X_test)

  scores.append(knn.score(X_test, y_test))

print(scores)

max_score = max(scores)
scores_ind = [i for i, v in enumerate(scores) if v == max_score]
scores_ind


knn = KNeighborsClassifier(3)

knn.fit(X_train, y_train)

y_pred = knn.predict(X_test)

confusion_matrix(y_test, y_pred)


print("Accuracy" , accuracy_score(y_test, y_pred))
print("Recall" ,recall_score(y_test, y_pred,average='macro'))
print("Precision" , precision_score(y_test, y_pred,average='macro'))

[0.60625, 0.5458333333333333, 0.5541666666666667, 0.5666666666666667, 0.5645833333333333, 0.5583333333333333, 0.5666666666666667, 0.5666666666666667, 0.5583333333333333, 0.5666666666666667, 0.5645833333333333, 0.5583333333333333, 0.5458333333333333, 0.5520833333333334]
Accuracy 0.5541666666666667
Recall 0.288504706212035
Precision 0.29229868549117377


/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [ ]:
# Метод ближайших соседей с помощью кроссвалиции (нормализованные данные)

kf = KFold(n_splits = 5)

tree = DecisionTreeClassifier()

cvs = cross_val_score(estimator = knn, X = X_norm, y = y, cv = kf, scoring = 'accuracy')

print(cvs)
print(cvs.mean())

[0.51875    0.459375   0.540625   0.425      0.49529781]
0.4878095611285267


In [ ]:
# Метод ближайших соседей для стандартизированных  данных
X_train, X_test, y_train, y_test = train_test_split(X_st, y, test_size=0.3, random_state = 42)

scores = []
for i in range(1,15):

  knn = KNeighborsClassifier(i)
  knn.fit(X_train, y_train)
  answers = knn.predict(X_test)

  scores.append(knn.score(X_test, y_test))

print(scores)

max_score = max(scores)
scores_ind = [i for i, v in enumerate(scores) if v == max_score]
scores_ind


knn = KNeighborsClassifier(3)

knn.fit(X_train, y_train)

y_pred = knn.predict(X_test)

confusion_matrix(y_test, y_pred)


print("Accuracy" , accuracy_score(y_test, y_pred))
print("Recall" ,recall_score(y_test, y_pred,average='macro'))
print("Precision" , precision_score(y_test, y_pred,average='macro'))

[0.625, 0.5625, 0.5395833333333333, 0.5520833333333334, 0.5708333333333333, 0.56875, 0.5604166666666667, 0.575, 0.5645833333333333, 0.5708333333333333, 0.5645833333333333, 0.575, 0.54375, 0.5604166666666667]
Accuracy 0.5395833333333333
Recall 0.27688918148175623
Precision 0.27963623185748965


/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [ ]:
# Метод ближайших соседей с помощью кроссвалиции (стандартизированные данные)

kf = KFold(n_splits = 5)

tree = DecisionTreeClassifier()

cvs = cross_val_score(estimator = knn, X = X_st, y = y, cv = kf, scoring = 'accuracy')

print(cvs)
print(cvs.mean())

[0.503125   0.48125    0.5375     0.46875    0.49216301]
0.4965576018808777


In [ ]:
# Дерево решений для нормализованных данных 
X_train,X_test,y_train,y_test = train_test_split(X_norm, y, test_size=1/3, random_state=42)

tree = DecisionTreeClassifier()


tree.fit(X_train, y_train)
y_pred_tree = tree.predict(X_test)


print("Accuracy" , accuracy_score(y_test, y_pred_tree, ))
print("Recall" ,recall_score(y_test, y_pred_tree, average='macro'))
print("Precision" , precision_score(y_test, y_pred_tree,average='macro' )) 

Accuracy 0.5628517823639775
Recall 0.31511922744341314
Precision 0.3144319527697162


/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [ ]:
# Дерево решений с помощью кроссвалидации (нормализованные данные)
# cross_val_score - возвращает массив оценок для каждого варианта разиения, 
# оценка модели в данном случае - это среднее
# n-splits - количество фолдов на которые хотим разделить

kf = KFold(n_splits=5)

# создаем модель 
tree = DecisionTreeClassifier(criterion='gini', max_depth=4, random_state=1)
# создаем кросс валидацию
# estimator - модель для которой применить кросс валидацию (логистическая регрессия, knn, дерево решений и т.д.)
# X - вектор признаков
# y - вектор ответов
# cv - параметры разбиения на фолды
# scoring - оценка по который оценить модель
cvs = cross_val_score(estimator=tree, X=X_norm, y=y, cv=kf, scoring='accuracy')

print(cvs)
print(cvs.mean())

[0.525      0.509375   0.5875     0.559375   0.59874608]
0.5559992163009405


In [ ]:
# Дерево решений для стандартизированных данных 
X_train,X_test,y_train,y_test = train_test_split(X_st, y, test_size=1/3, random_state=42)

tree = DecisionTreeClassifier()


tree.fit(X_train, y_train)
y_pred_tree = tree.predict(X_test)


print("Accuracy" , accuracy_score(y_test, y_pred_tree,))
print("Recall" ,recall_score(y_test, y_pred_tree, average='macro'))
print("Precision" , precision_score(y_test, y_pred_tree,average='macro' )) 

Accuracy 0.5553470919324578
Recall 0.31196181708625764
Precision 0.3110780031748538


In [ ]:
# Дерево решений с помощью кроссвалидации (стандартизированные данные)
# cross_val_score - возвращает массив оценок для каждого варианта разиения, 
# оценка модели в данном случае - это среднее
# n-splits - количество фолдов на которые хотим разделить

kf = KFold(n_splits=5)

# создаем модель 
tree = DecisionTreeClassifier(criterion='gini', max_depth=4, random_state=1)
# создаем кросс валидацию
# estimator - модель для которой применить кросс валидацию (логистическая регрессия, knn, дерево решений и т.д.)
# X - вектор признаков
# y - вектор ответов
# cv - параметры разбиения на фолды
# scoring - оценка по который оценить модель
cvs = cross_val_score(estimator=tree, X=X_st, y=y, cv=kf, scoring='accuracy')

print(cvs)
print(cvs.mean())

[0.521875   0.509375   0.5875     0.559375   0.59874608]
0.5553742163009404


In [ ]:
# Метод опорных векторов для нормализованных данных
X_train,X_test,y_train,y_test = train_test_split(X_norm, y, test_size=1/3, random_state=42)

svm = SVC()

svm.fit(X_train, y_train)
y_pred_svm = svm.predict(X_test)
print("Accuracy" , accuracy_score(y_test, y_pred_tree,))
print("Recall" ,recall_score(y_test, y_pred_tree, average='macro'))
print("Precision" , precision_score(y_test, y_pred_tree,average='macro' )) 

Accuracy 0.5553470919324578
Recall 0.31196181708625764
Precision 0.3110780031748538


In [ ]:
# Метод опорных векторов с помощью кроссвалидации (нормализованные данные)
kf = KFold(n_splits = 5)

tree = DecisionTreeClassifier()

cvs = cross_val_score(estimator = svm, X = X_norm, y = y, cv = kf, scoring = 'accuracy')

print(cvs)
print(cvs.mean())

[0.596875   0.521875   0.59375    0.584375   0.60501567]
0.5803781347962382


In [ ]:
# Метод опорных векторов для стандартизированных данных
X_train,X_test,y_train,y_test = train_test_split(X_st, y, test_size=1/3, random_state=42)

svm = SVC()

svm.fit(X_train, y_train)
y_pred_svm = svm.predict(X_test)
print("Accuracy" , accuracy_score(y_test, y_pred_tree,))
print("Recall" ,recall_score(y_test, y_pred_tree, average='macro'))
print("Precision" , precision_score(y_test, y_pred_tree,average='macro' )) 

Accuracy 0.5553470919324578
Recall 0.31196181708625764
Precision 0.3110780031748538


In [ ]:
# Метод опорных векторов с помощью кроссвалидации (стандартизированные данные)
kf = KFold(n_splits = 5)

tree = DecisionTreeClassifier()

cvs = cross_val_score(estimator = svm, X = X_st, y = y, cv = kf, scoring = 'accuracy')

print(cvs)
print(cvs.mean())

[0.60625    0.521875   0.609375   0.5875     0.62382445]
0.5897648902821316


In [ ]:
# Лучшим в плане accuracy оказалась логистическая регрессия с использованием кроссвалидации (нормализованные данные)
# Лучшим в плане recall оказалось дерево решений для нормализованных данных 
# Лучшим в плане precision оказалось дерево решений для нормализованных данных

# В данной работе были исследованы данные: ,, столько то классов в нашей работе, оценили различные модели и пришли к выводу что наилучшая модель такая то по следующим причинам ..."
# Размерность данных 1599 rows × 12 columns
# Пропусков во всем df 0
# Категориальных признаков не было, все признаки были уже числовыми
# В качестве признаков взяли столбец quality
# В качестве ответов взяли столбец quality
# В нашей работе 2 типа данных float64 и int64 
# В нашей работе мы оценили различные модели и пришли к выводу, что наилучшей моделью оказалось дерево решений для нормализованных данных