In [2]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import KFold
from sklearn.metrics import accuracy_score
from sklearn.metrics import recall_score
from sklearn.metrics import precision_score
from sklearn.tree import DecisionTreeClassifier
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import confusion_matrix
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC

In [3]:
from google.colab import files 
uploaded = files.upload()

Saving house-votes-84.csv to house-votes-84.csv


In [4]:
df = pd.read_csv("house-votes-84.csv")
df
## Считываем датасет

Class Name  ...  export-administration-act-south-africa
0    republican  ...                                       y
1    republican  ...                                       ?
2      democrat  ...                                       n
3      democrat  ...                                       y
4      democrat  ...                                       y
..          ...  ...                                     ...
430  republican  ...                                       y
431    democrat  ...                                       y
432  republican  ...                                       y
433  republican  ...                                       y
434  republican  ...                                       n

[435 rows x 17 columns]

In [5]:
print(df.shape)
## Определяем размерность датафрейма

(435, 17)


In [6]:
df.info()
# Определяем тип данных в каждом столбце

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 435 entries, 0 to 434
Data columns (total 17 columns):
 #   Column                                   Non-Null Count  Dtype 
---  ------                                   --------------  ----- 
 0   Class Name                               435 non-null    object
 1    handicapped-infants                     435 non-null    object
 2    water-project-cost-sharing              435 non-null    object
 3    adoption-of-the-budget-resolution       435 non-null    object
 4    physician-fee-freeze                    435 non-null    object
 5    el-salvador-aid                         435 non-null    object
 6    religious-groups-in-schools             435 non-null    object
 7    anti-satellite-test-ban                 435 non-null    object
 8    aid-to-nicaraguan-contras               435 non-null    object
 9    mx-missile                              435 non-null    object
 10   immigration                             435 non-null    objec

In [7]:
print(df.isna().sum())
## Ищем пустые значения

Class Name                                 0
 handicapped-infants                       0
 water-project-cost-sharing                0
 adoption-of-the-budget-resolution         0
 physician-fee-freeze                      0
 el-salvador-aid                           0
 religious-groups-in-schools               0
 anti-satellite-test-ban                   0
 aid-to-nicaraguan-contras                 0
 mx-missile                                0
 immigration                               0
 synfuels-corporation-cutback              0
 education-spending                        0
 superfund-right-to-sue                    0
 crime                                     0
 duty-free-exports                         0
 export-administration-act-south-africa    0
dtype: int64


In [8]:
df[' handicapped-infants'] = df[' handicapped-infants'].map({'n': 0,
'y': 1})
df[' water-project-cost-sharing'] = df[' water-project-cost-sharing'].map({'n': 0,
'y': 1})
df[' adoption-of-the-budget-resolution'] = df[' adoption-of-the-budget-resolution'].map({'n': 0,
'y': 1})
df[' physician-fee-freeze'] = df[' physician-fee-freeze'].map({'n': 0,
'y': 1})
df[' el-salvador-aid'] = df[' el-salvador-aid'].map({'n': 0,
'y': 1})
df[' religious-groups-in-schools'] = df[' religious-groups-in-schools'].map({'n': 0,
'y': 1})
df[' anti-satellite-test-ban'] = df[' anti-satellite-test-ban'].map({'n': 0,
'y': 1})
df[' mx-missile'] = df[' mx-missile'].map({'n': 0,
'y': 1})
df[' immigration'] = df[' immigration'].map({'n': 0,
'y': 1})
df[' synfuels-corporation-cutback'] = df[' synfuels-corporation-cutback'].map({'n': 0,
'y': 1})
df[' education-spending'] = df[' education-spending'].map({'n': 0,
'y': 1})
df[' superfund-right-to-sue'] = df[' superfund-right-to-sue'].map({'n': 0,
'y': 1})
df[' crime'] = df[' crime'].map({'n': 0,
'y': 1})
df[' export-administration-act-south-africa'] = df[' export-administration-act-south-africa'].map({'n': 0,
'y': 1})
df[' aid-to-nicaraguan-contras'] = df[' aid-to-nicaraguan-contras'].map({'n': 0,
'y': 1})
df[' duty-free-exports'] = df[' duty-free-exports'].map({'n': 0,
'y': 1})
df['Class Name'] = df['Class Name'].map({'republican': 0,
'democrat': 1})
## Заменяем строчные значения на числовые

In [9]:
df.isna().sum()
# После замены значений появились пустые значения

Class Name                                   0
 handicapped-infants                        12
 water-project-cost-sharing                 48
 adoption-of-the-budget-resolution          11
 physician-fee-freeze                       11
 el-salvador-aid                            15
 religious-groups-in-schools                11
 anti-satellite-test-ban                    14
 aid-to-nicaraguan-contras                  15
 mx-missile                                 22
 immigration                                 7
 synfuels-corporation-cutback               21
 education-spending                         31
 superfund-right-to-sue                     25
 crime                                      17
 duty-free-exports                          28
 export-administration-act-south-africa    104
dtype: int64

In [10]:
df = df.drop([' export-administration-act-south-africa'] , axis=1)
# Удаляем столбец в котором слишком много пустых значений

In [11]:
df

Class Name   handicapped-infants  ...   crime   duty-free-exports
0             0                   0.0  ...     1.0                 0.0
1             0                   0.0  ...     1.0                 0.0
2             1                   NaN  ...     1.0                 0.0
3             1                   0.0  ...     0.0                 0.0
4             1                   1.0  ...     1.0                 1.0
..          ...                   ...  ...     ...                 ...
430           0                   0.0  ...     1.0                 0.0
431           1                   0.0  ...     0.0                 0.0
432           0                   0.0  ...     1.0                 0.0
433           0                   0.0  ...     1.0                 0.0
434           0                   0.0  ...     1.0                 NaN

[435 rows x 16 columns]

In [12]:
df = df.dropna()
df
# Удаляем все строки с пустыми значениями

Class Name   handicapped-infants  ...   crime   duty-free-exports
1             0                   0.0  ...     1.0                 0.0
5             1                   0.0  ...     1.0                 1.0
8             0                   0.0  ...     1.0                 0.0
19            1                   1.0  ...     0.0                 1.0
23            1                   1.0  ...     0.0                 1.0
..          ...                   ...  ...     ...                 ...
425           1                   0.0  ...     0.0                 1.0
426           1                   1.0  ...     0.0                 1.0
427           0                   0.0  ...     1.0                 0.0
430           0                   0.0  ...     1.0                 0.0
431           1                   0.0  ...     0.0                 0.0

[281 rows x 16 columns]

In [13]:
X =  df.drop(['Class Name'], axis = 1)
y = df['Class Name']
# Задаем вектор признаков

In [14]:
# Логистическая регрессия для немасштабированных данных
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state = 42)
model = LogisticRegression()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)

print("Accuracy" , accuracy_score(y_test, y_pred))
print("Recall" ,recall_score(y_test, y_pred))
print("Precision" , precision_score(y_test, y_pred)) 

Accuracy 0.9411764705882353
Recall 0.9259259259259259
Precision 0.9803921568627451


In [15]:
# Метод ближайших соседей для немасштабированных данных
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state = 42)

scores = []
for i in range(1,15):

  knn = KNeighborsClassifier(i)
  knn.fit(X_train, y_train)
  answers = knn.predict(X_test)

  scores.append(knn.score(X_test, y_test))

print(scores)


max_score = max(scores)
scores_ind = [i for i, v in enumerate(scores) if v == max_score]
scores_ind



knn = KNeighborsClassifier(3)

knn.fit(X_train, y_train)

y_pred = knn.predict(X_test)

confusion_matrix(y_test, y_pred)




print("Accuracy" , accuracy_score(y_test, y_pred))
print("Recall" ,recall_score(y_test, y_pred))
print("Precision" , precision_score(y_test, y_pred)) 

[0.9411764705882353, 0.9058823529411765, 0.9294117647058824, 0.9176470588235294, 0.9176470588235294, 0.9058823529411765, 0.9176470588235294, 0.9176470588235294, 0.9176470588235294, 0.9176470588235294, 0.9294117647058824, 0.9176470588235294, 0.9294117647058824, 0.9176470588235294]
Accuracy 0.9294117647058824
Recall 0.9074074074074074
Precision 0.98


In [16]:
# Дерево решений для немасштабированных данных
X_train,X_test,y_train,y_test = train_test_split(X, y, test_size=1/3, random_state=42)

tree = DecisionTreeClassifier()


tree.fit(X_train, y_train)
y_pred_tree = tree.predict(X_test)


print("Accuracy" , accuracy_score(y_test, y_pred_tree))
print("Recall" ,recall_score(y_test, y_pred_tree))
print("Precision" , precision_score(y_test, y_pred_tree)) 

Accuracy 0.9574468085106383
Recall 0.95
Precision 0.9827586206896551


In [17]:
# Метод опорных векторов для немасштабированных данных
X_train,X_test,y_train,y_test = train_test_split(X, y, test_size=1/3, random_state=42)

svm = SVC()

svm.fit(X_train, y_train)
y_pred_svm = svm.predict(X_test)

print("Accuracy:", accuracy_score(y_test,y_pred_svm))
print("Recall:", recall_score(y_test,y_pred_svm))
print("Precision:", precision_score(y_test,y_pred_svm))

Accuracy: 0.9468085106382979
Recall: 0.9333333333333333
Precision: 0.9824561403508771


In [18]:
# логистическая регрессия с помощью кросс-валидации (для немасштабированных данных)

X_train, X_test, y_train, y_test = train_test_split(X ,y, test_size=0.3, random_state = 42)
model = LogisticRegression()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)

print("Accuracy" , accuracy_score(y_test, y_pred))
print("Recall" ,recall_score(y_test, y_pred))
print("Precision" , precision_score(y_test, y_pred)) 
confusion_matrix(y_test, y_pred)


print('_______________________________________________________')



kf = KFold(n_splits = 5)

model = LogisticRegression()

cvs = cross_val_score(estimator = model, X = X, y = y, cv = kf, scoring = 'accuracy')

print(cvs)
print(cvs.mean())

Accuracy 0.9411764705882353
Recall 0.9259259259259259
Precision 0.9803921568627451
_______________________________________________________
[0.94736842 0.96428571 0.96428571 0.98214286 0.89285714]
0.9501879699248121


In [19]:
#дерево решений с помощью кросс-валидации для немасштабированных данных

X_train,X_test,y_train,y_test = train_test_split(X, y, test_size=1/3, random_state=42)

tree = DecisionTreeClassifier()


tree.fit(X_train, y_train)
y_pred_tree = tree.predict(X_test)


print("Accuracy" , accuracy_score(y_test, y_pred_tree))
print("Recall" ,recall_score(y_test, y_pred_tree))
print("Precision" , precision_score(y_test, y_pred_tree)) 


kf = KFold(n_splits = 5)

tree = DecisionTreeClassifier()

cvs = cross_val_score(estimator = tree, X = X, y = y, cv = kf, scoring = 'accuracy')

print(cvs)
print(cvs.mean())

Accuracy 0.9574468085106383
Recall 0.95
Precision 0.9827586206896551
[0.94736842 0.94642857 0.96428571 1.         0.875     ]
0.9466165413533835


In [20]:
# метод ближайших соседей с помощью кросс-валидации для немасштабированных данных

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state = 42)

scores = []
for i in range(1,15):

  knn = KNeighborsClassifier(i)
  knn.fit(X_train, y_train)
  answers = knn.predict(X_test)

  scores.append(knn.score(X_test, y_test))

print(scores)


max_score = max(scores)
scores_ind = [i for i, v in enumerate(scores) if v == max_score]
scores_ind




knn = KNeighborsClassifier(7)

knn.fit(X_train, y_train)

y_pred = knn.predict(X_test)

confusion_matrix(y_test, y_pred)




print("Accuracy" , accuracy_score(y_test, y_pred))
print("Recall" ,recall_score(y_test, y_pred))
print("Precision" , precision_score(y_test, y_pred)) 



kf = KFold(n_splits = 5)

knn = KNeighborsClassifier(i)

cvs = cross_val_score(estimator = knn, X = X, y = y, cv = kf, scoring = 'accuracy')

print(cvs)
print(cvs.mean())

[0.9411764705882353, 0.9058823529411765, 0.9294117647058824, 0.9176470588235294, 0.9176470588235294, 0.9058823529411765, 0.9176470588235294, 0.9176470588235294, 0.9176470588235294, 0.9176470588235294, 0.9294117647058824, 0.9176470588235294, 0.9294117647058824, 0.9176470588235294]
Accuracy 0.9176470588235294
Recall 0.8888888888888888
Precision 0.9795918367346939
[0.89473684 0.83928571 0.96428571 1.         0.85714286]
0.9110902255639097


In [21]:
# метод опорных векторов с помощью кросс-валидации для немасштабированных данных
X_train,X_test,y_train,y_test = train_test_split(X, y, test_size=1/3, random_state=42)

svm = SVC()

svm.fit(X_train, y_train)
y_pred_svm = svm.predict(X_test)

print("Accuracy:", accuracy_score(y_test,y_pred_svm))
print("Recall:", recall_score(y_test,y_pred_svm))
print("Precision:", precision_score(y_test,y_pred_svm))



kf = KFold(n_splits = 5)

svm = SVC()

cvs = cross_val_score(estimator = svm, X = X, y = y, cv = kf, scoring = 'accuracy')

print(cvs)
print(cvs.mean())


Accuracy: 0.9468085106382979
Recall: 0.9333333333333333
Precision: 0.9824561403508771
[0.94736842 0.96428571 0.96428571 0.98214286 0.91071429]
0.9537593984962406


In [22]:
scaler = MinMaxScaler()
X_norm = scaler.fit_transform(X)
X_norm
# Нормализируем данные

array([[0., 1., 0., ..., 1., 1., 0.],
       [0., 1., 1., ..., 1., 1., 1.],
       [0., 1., 0., ..., 1., 1., 0.],
       ...,
       [0., 0., 0., ..., 1., 1., 0.],
       [0., 0., 1., ..., 1., 1., 0.],
       [0., 0., 1., ..., 0., 0., 0.]])

In [23]:
#дерево решений для нормализованных данных 

X_train,X_test,y_train,y_test = train_test_split(X_norm, y, test_size=1/3, random_state=42)

tree = DecisionTreeClassifier()


tree.fit(X_train, y_train)
y_pred_tree = tree.predict(X_test)


print("Accuracy" , accuracy_score(y_test, y_pred_tree))
print("Recall" ,recall_score(y_test, y_pred_tree))
print("Precision" , precision_score(y_test, y_pred_tree)) 

Accuracy 0.9574468085106383
Recall 0.95
Precision 0.9827586206896551


In [24]:
#дерево решений с помощью кросс-валидации(норм. данные)

X_train,X_test,y_train,y_test = train_test_split(X_norm, y, test_size=1/3, random_state=42)

tree = DecisionTreeClassifier()


tree.fit(X_train, y_train)
y_pred_tree = tree.predict(X_test)


print("Accuracy" , accuracy_score(y_test, y_pred_tree))
print("Recall" ,recall_score(y_test, y_pred_tree))
print("Precision" , precision_score(y_test, y_pred_tree)) 


kf = KFold(n_splits = 5)

tree = DecisionTreeClassifier()

cvs = cross_val_score(estimator = tree, X = X_norm, y = y, cv = kf, scoring = 'accuracy')

print(cvs)
print(cvs.mean())

Accuracy 0.9574468085106383
Recall 0.95
Precision 0.9827586206896551
[0.96491228 0.96428571 0.96428571 0.98214286 0.89285714]
0.9536967418546366


In [25]:
scaler = StandardScaler()
X_st = scaler.fit_transform(X)
X_st
# Cтандартизируем данные

array([[-0.88871194,  1.07774694, -1.1667667 , ...,  0.94797081,
         0.79011231, -0.81407733],
       [-0.88871194,  1.07774694,  0.85706937, ...,  0.94797081,
         0.79011231,  1.22838454],
       [-0.88871194,  1.07774694, -1.1667667 , ...,  0.94797081,
         0.79011231, -0.81407733],
       ...,
       [-0.88871194, -0.9278616 , -1.1667667 , ...,  0.94797081,
         0.79011231, -0.81407733],
       [-0.88871194, -0.9278616 ,  0.85706937, ...,  0.94797081,
         0.79011231, -0.81407733],
       [-0.88871194, -0.9278616 ,  0.85706937, ..., -1.05488481,
        -1.26564286, -0.81407733]])

In [26]:
#дерево решений для стандартизированных данных 

X_train,X_test,y_train,y_test = train_test_split(X_st, y, test_size=1/3, random_state=42)

tree = DecisionTreeClassifier()


tree.fit(X_train, y_train)
y_pred_tree = tree.predict(X_test)


print("Accuracy" , accuracy_score(y_test, y_pred_tree))
print("Recall" ,recall_score(y_test, y_pred_tree))
print("Precision" , precision_score(y_test, y_pred_tree)) 

Accuracy 0.9574468085106383
Recall 0.95
Precision 0.9827586206896551


In [27]:
#дерево решений с помощью кросс-валидации(ст. данные)

X_train,X_test,y_train,y_test = train_test_split(X_st, y, test_size=1/3, random_state=42)

tree = DecisionTreeClassifier()


tree.fit(X_train, y_train)
y_pred_tree = tree.predict(X_test)


print("Accuracy" , accuracy_score(y_test, y_pred_tree))
print("Recall" ,recall_score(y_test, y_pred_tree))
print("Precision" , precision_score(y_test, y_pred_tree)) 


kf = KFold(n_splits = 5)

tree = DecisionTreeClassifier()

cvs = cross_val_score(estimator = tree, X = X_st, y = y, cv = kf, scoring = 'accuracy')

print(cvs)
print(cvs.mean())

Accuracy 0.9574468085106383
Recall 0.95
Precision 0.9827586206896551
[0.96491228 0.96428571 0.96428571 1.         0.91071429]
0.9608395989974937


In [28]:
#логистическая регрессия для нормализованных данных

X_train, X_test, y_train, y_test = train_test_split(X_norm,y, test_size=0.3, random_state = 42)
model = LogisticRegression()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)

print("Accuracy" , accuracy_score(y_test, y_pred))
print("Recall" ,recall_score(y_test, y_pred))
print("Precision" , precision_score(y_test, y_pred)) 

Accuracy 0.9411764705882353
Recall 0.9259259259259259
Precision 0.9803921568627451


In [29]:
#логистическая регрессия для стандартизированных данных
X_train, X_test, y_train, y_test = train_test_split(X_st,y, test_size=0.3, random_state = 42)
model = LogisticRegression()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)

print("Accuracy" , accuracy_score(y_test, y_pred))
print("Recall" ,recall_score(y_test, y_pred))
print("Precision" , precision_score(y_test, y_pred)) 

Accuracy 0.9647058823529412
Recall 0.9629629629629629
Precision 0.9811320754716981


In [30]:
# метод ближайших соседей (для стандартизированных  данных)
X_train, X_test, y_train, y_test = train_test_split(X_st, y, test_size=0.3, random_state = 42)

scores = []
for i in range(1,15):

  knn = KNeighborsClassifier(i)
  knn.fit(X_train, y_train)
  answers = knn.predict(X_test)

  scores.append(knn.score(X_test, y_test))

print(scores)


max_score = max(scores)
scores_ind = [i for i, v in enumerate(scores) if v == max_score]
scores_ind



knn = KNeighborsClassifier(3)

knn.fit(X_train, y_train)

y_pred = knn.predict(X_test)

confusion_matrix(y_test, y_pred)




print("Accuracy" , accuracy_score(y_test, y_pred))
print("Recall" ,recall_score(y_test, y_pred))
print("Precision" , precision_score(y_test, y_pred)) 


[0.9294117647058824, 0.9294117647058824, 0.9411764705882353, 0.9176470588235294, 0.9411764705882353, 0.9294117647058824, 0.9294117647058824, 0.9176470588235294, 0.9294117647058824, 0.9294117647058824, 0.9411764705882353, 0.9294117647058824, 0.9294117647058824, 0.9294117647058824]
Accuracy 0.9411764705882353
Recall 0.9259259259259259
Precision 0.9803921568627451


In [31]:
# метод ближайших соседей (для нормализованных данных)

X_train, X_test, y_train, y_test = train_test_split(X_norm, y, test_size=0.3, random_state = 42)

scores = []
for i in range(1,15):

  knn = KNeighborsClassifier(i)
  knn.fit(X_train, y_train)
  answers = knn.predict(X_test)

  scores.append(knn.score(X_test, y_test))

print(scores)


max_score = max(scores)
scores_ind = [i for i, v in enumerate(scores) if v == max_score]
scores_ind


knn = KNeighborsClassifier(1)

knn.fit(X_train, y_train)

y_pred = knn.predict(X_test)

confusion_matrix(y_test, y_pred)




print("Accuracy" , accuracy_score(y_test, y_pred))
print("Recall" ,recall_score(y_test, y_pred))
print("Precision" , precision_score(y_test, y_pred))

 

[0.9411764705882353, 0.9058823529411765, 0.9294117647058824, 0.9176470588235294, 0.9176470588235294, 0.9058823529411765, 0.9176470588235294, 0.9176470588235294, 0.9176470588235294, 0.9176470588235294, 0.9294117647058824, 0.9176470588235294, 0.9294117647058824, 0.9176470588235294]
Accuracy 0.9411764705882353
Recall 0.9259259259259259
Precision 0.9803921568627451


In [32]:
# логистическая регрессия с помощью кросс-валидации (для нормализованных данных)

X_train, X_test, y_train, y_test = train_test_split(X_norm,y, test_size=0.3, random_state = 42)
model = LogisticRegression()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)

print("Accuracy" , accuracy_score(y_test, y_pred))
print("Recall" ,recall_score(y_test, y_pred))
print("Precision" , precision_score(y_test, y_pred)) 
confusion_matrix(y_test, y_pred)


print('_______________________________________________________')



kf = KFold(n_splits = 5)

model = LogisticRegression()

cvs = cross_val_score(estimator = model, X = X_norm, y = y, cv = kf, scoring = 'accuracy')

print(cvs)
print(cvs.mean())

Accuracy 0.9411764705882353
Recall 0.9259259259259259
Precision 0.9803921568627451
_______________________________________________________
[0.94736842 0.96428571 0.96428571 0.98214286 0.89285714]
0.9501879699248121


In [33]:
# логистическая регрессия с помощью кросс-валидации (для стандартизированных данных)

X_train, X_test, y_train, y_test = train_test_split(X_st,y, test_size=0.3, random_state = 42)
model = LogisticRegression()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)

print("Accuracy" , accuracy_score(y_test, y_pred))
print("Recall" ,recall_score(y_test, y_pred))
print("Precision" , precision_score(y_test, y_pred)) 
confusion_matrix(y_test, y_pred)


print('_______________________________________________________')



kf = KFold(n_splits = 5)

model = LogisticRegression()

cvs = cross_val_score(estimator = model, X = X_st, y = y, cv = kf, scoring = 'accuracy')

print(cvs)
print(cvs.mean())

Accuracy 0.9647058823529412
Recall 0.9629629629629629
Precision 0.9811320754716981
_______________________________________________________
[0.96491228 0.96428571 0.96428571 0.98214286 0.92857143]
0.9608395989974937


In [34]:
# метод ближайших соседей с помощью кросс-валидации (для нормализованных данных)

X_train, X_test, y_train, y_test = train_test_split(X_norm, y, test_size=0.3, random_state = 42)

scores = []
for i in range(1,15):

  knn = KNeighborsClassifier(i)
  knn.fit(X_train, y_train)
  answers = knn.predict(X_test)

  scores.append(knn.score(X_test, y_test))

print(scores)


max_score = max(scores)
scores_ind = [i for i, v in enumerate(scores) if v == max_score]
scores_ind




knn = KNeighborsClassifier(7)

knn.fit(X_train, y_train)

y_pred = knn.predict(X_test)

confusion_matrix(y_test, y_pred)




print("Accuracy" , accuracy_score(y_test, y_pred))
print("Recall" ,recall_score(y_test, y_pred))
print("Precision" , precision_score(y_test, y_pred)) 



kf = KFold(n_splits = 5)

knn = KNeighborsClassifier(i)

cvs = cross_val_score(estimator = knn, X = X_norm, y = y, cv = kf, scoring = 'accuracy')

print(cvs)
print(cvs.mean())

[0.9411764705882353, 0.9058823529411765, 0.9294117647058824, 0.9176470588235294, 0.9176470588235294, 0.9058823529411765, 0.9176470588235294, 0.9176470588235294, 0.9176470588235294, 0.9176470588235294, 0.9294117647058824, 0.9176470588235294, 0.9294117647058824, 0.9176470588235294]
Accuracy 0.9176470588235294
Recall 0.8888888888888888
Precision 0.9795918367346939
[0.89473684 0.83928571 0.96428571 1.         0.85714286]
0.9110902255639097


In [35]:
# метод ближайших соседей с помощью кросс-валидации (для стандартизированных данных)

X_train, X_test, y_train, y_test = train_test_split(X_st, y, test_size=0.3, random_state = 42)

scores = []
for i in range(1,15):

  knn = KNeighborsClassifier(i)
  knn.fit(X_train, y_train)
  answers = knn.predict(X_test)

  scores.append(knn.score(X_test, y_test))

print(scores)


max_score = max(scores)
scores_ind = [i for i, v in enumerate(scores) if v == max_score]
scores_ind




knn = KNeighborsClassifier(7)

knn.fit(X_train, y_train)

y_pred = knn.predict(X_test)

confusion_matrix(y_test, y_pred)




print("Accuracy" , accuracy_score(y_test, y_pred))
print("Recall" ,recall_score(y_test, y_pred))
print("Precision" , precision_score(y_test, y_pred)) 



kf = KFold(n_splits = 5)

knn = KNeighborsClassifier(i)

cvs = cross_val_score(estimator = knn, X = X_st, y = y, cv = kf, scoring = 'accuracy')

print(cvs)
print(cvs.mean())

[0.9294117647058824, 0.9294117647058824, 0.9411764705882353, 0.9176470588235294, 0.9411764705882353, 0.9294117647058824, 0.9294117647058824, 0.9176470588235294, 0.9294117647058824, 0.9294117647058824, 0.9411764705882353, 0.9294117647058824, 0.9294117647058824, 0.9294117647058824]
Accuracy 0.9294117647058824
Recall 0.9074074074074074
Precision 0.98
[0.9122807  0.83928571 0.96428571 1.         0.875     ]
0.9181704260651629


In [36]:
#метод опорных векторов для нормализованных данных

X_train,X_test,y_train,y_test = train_test_split(X_norm, y, test_size=1/3, random_state=42)

svm = SVC()

svm.fit(X_train, y_train)
y_pred_svm = svm.predict(X_test)

print("Accuracy:", accuracy_score(y_test,y_pred_svm))
print("Recall:", recall_score(y_test,y_pred_svm))
print("Precision:", precision_score(y_test,y_pred_svm))

Accuracy: 0.9468085106382979
Recall: 0.9333333333333333
Precision: 0.9824561403508771


In [37]:
#метод опорных векторов для стандартизированных данных

X_train,X_test,y_train,y_test = train_test_split(X_st, y, test_size=1/3, random_state=42)

svm = SVC()

svm.fit(X_train, y_train)
y_pred_svm = svm.predict(X_test)

print("Accuracy:", accuracy_score(y_test,y_pred_svm))
print("Recall:", recall_score(y_test,y_pred_svm))
print("Precision:", precision_score(y_test,y_pred_svm))

Accuracy: 0.9468085106382979
Recall: 0.9333333333333333
Precision: 0.9824561403508771


In [38]:
#метод опорных векторов для нормализованных данных с кроссвалидацией 

X_train,X_test,y_train,y_test = train_test_split(X_norm, y, test_size=1/3, random_state=42)

svm = SVC()

svm.fit(X_train, y_train)
y_pred_svm = svm.predict(X_test)

print("Accuracy:", accuracy_score(y_test,y_pred_svm))
print("Recall:", recall_score(y_test,y_pred_svm))
print("Precision:", precision_score(y_test,y_pred_svm))



kf = KFold(n_splits = 5)


svm = SVC()

cvs = cross_val_score(estimator = svm, X = X_norm, y = y, cv = kf, scoring = 'accuracy')

print(cvs)
print(cvs.mean())


Accuracy: 0.9468085106382979
Recall: 0.9333333333333333
Precision: 0.9824561403508771
[0.94736842 0.96428571 0.96428571 0.98214286 0.91071429]
0.9537593984962406


In [39]:
#метод опорных векторов для стандартизированных данных с кроссвалидацией 

X_train,X_test,y_train,y_test = train_test_split(X_st, y, test_size=1/3, random_state=42)

svm = SVC()

svm.fit(X_train, y_train)
y_pred_svm = svm.predict(X_test)

print("Accuracy:", accuracy_score(y_test,y_pred_svm))
print("Recall:", recall_score(y_test,y_pred_svm))
print("Precision:", precision_score(y_test,y_pred_svm))



kf = KFold(n_splits = 5)

svm = SVC()

cvs = cross_val_score(estimator = svm, X = X_st, y = y, cv = kf, scoring = 'accuracy')

print(cvs)
print(cvs.mean())

Accuracy: 0.9468085106382979
Recall: 0.9333333333333333
Precision: 0.9824561403508771
[0.94736842 0.94642857 0.96428571 0.98214286 0.91071429]
0.9501879699248121


In [40]:
# На основе полученных данных мы можем сделать вывод, что самой лучшей моделью является логистическая регрессия на стандартизированных данных