In [27]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [6]:
di= pd.read_csv("drive/My Drive/diabetes.csv" )
di

Pregnancies  Glucose  ...  Age  Outcome
0              6      148  ...   50        1
1              1       85  ...   31        0
2              8      183  ...   32        1
3              1       89  ...   21        0
4              0      137  ...   33        1
..           ...      ...  ...  ...      ...
763           10      101  ...   63        0
764            2      122  ...   27        0
765            5      121  ...   30        0
766            1      126  ...   47        1
767            1       93  ...   23        0

[768 rows x 9 columns]

In [7]:
print(di.shape)

(768, 9)


In [11]:
print(di[di['Outcome'] ==1].shape)
print(di[di['Outcome'] ==0].shape)
print(di.info())
print(di.isna().sum())
y = di['Outcome']
x = di.drop(['Outcome'], axis=1)

(268, 9)
(500, 9)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   Pregnancies               768 non-null    int64  
 1   Glucose                   768 non-null    int64  
 2   BloodPressure             768 non-null    int64  
 3   SkinThickness             768 non-null    int64  
 4   Insulin                   768 non-null    int64  
 5   BMI                       768 non-null    float64
 6   DiabetesPedigreeFunction  768 non-null    float64
 7   Age                       768 non-null    int64  
 8   Outcome                   768 non-null    int64  
dtypes: float64(2), int64(7)
memory usage: 54.1 KB
None
Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age    

In [81]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_st = scaler.fit_transform(x)

X_st

array([[ 0.63994726,  0.84832379,  0.14964075, ...,  0.20401277,
         0.46849198,  1.4259954 ],
       [-0.84488505, -1.12339636, -0.16054575, ..., -0.68442195,
        -0.36506078, -0.19067191],
       [ 1.23388019,  1.94372388, -0.26394125, ..., -1.10325546,
         0.60439732, -0.10558415],
       ...,
       [ 0.3429808 ,  0.00330087,  0.14964075, ..., -0.73518964,
        -0.68519336, -0.27575966],
       [-0.84488505,  0.1597866 , -0.47073225, ..., -0.24020459,
        -0.37110101,  1.17073215],
       [-0.84488505, -0.8730192 ,  0.04624525, ..., -0.20212881,
        -0.47378505, -0.87137393]])

In [24]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
X_norm = scaler.fit_transform(x)
X_norm

array([[0.35294118, 0.74371859, 0.59016393, ..., 0.50074516, 0.23441503,
        0.48333333],
       [0.05882353, 0.42713568, 0.54098361, ..., 0.39642325, 0.11656704,
        0.16666667],
       [0.47058824, 0.91959799, 0.52459016, ..., 0.34724292, 0.25362938,
        0.18333333],
       ...,
       [0.29411765, 0.6080402 , 0.59016393, ..., 0.390462  , 0.07130658,
        0.15      ],
       [0.05882353, 0.63316583, 0.49180328, ..., 0.4485842 , 0.11571307,
        0.43333333],
       [0.05882353, 0.46733668, 0.57377049, ..., 0.45305514, 0.10119556,
        0.03333333]])

In [96]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.3)
scores =[]
for i in range(1,15):
  knn = KNeighborsClassifier(i)
  knn.fit(X_train,y_train)
  answers = knn.predict(X_test)
  scores.append(knn.score(X_test,y_test))
print(scores)

[0.6753246753246753, 0.6493506493506493, 0.6926406926406926, 0.6666666666666666, 0.6796536796536796, 0.6883116883116883, 0.6883116883116883, 0.696969696969697, 0.7012987012987013, 0.7056277056277056, 0.7012987012987013, 0.7012987012987013, 0.7012987012987013, 0.70995670995671]


In [58]:
max_score = max(scores)
scores_ind = [ i for i, v in enumerate(scores) if v == max_score]
scores_ind

[4, 6]

In [60]:
knn = KNeighborsClassifier(5)
knn.fit(X_train,y_train)
y_pred = knn.predict(X_test)
confusion_matrix(y_test,y_pred)

array([[125,  30],
       [ 37,  39]])

In [86]:
from sklearn.metrics import accuracy_score
from sklearn.metrics import recall_score
from sklearn.metrics import precision_score
print("Accuracy: ", accuracy_score(y_test,y_pred))
print("Recall: ", recall_score(y_test,y_pred))
print("Precision: ", precision_score(y_test,y_pred))

Accuracy:  0.5411255411255411
Recall:  0.2716049382716049
Precision:  0.3188405797101449


In [97]:
X_train, X_test, y_train, y_test = train_test_split(X_st,y, test_size=0.3)
scores =[]
for i in range(1,15):
  knn = KNeighborsClassifier(i)
  knn.fit(X_train,y_train)
  answers = knn.predict(X_test)
  scores.append(knn.score(X_test,y_test))
print(scores)

print("Accuracy: ", accuracy_score(y_test,y_pred))
print("Recall: ", recall_score(y_test,y_pred))
print("Precision: ", precision_score(y_test,y_pred))

[0.6406926406926406, 0.6493506493506493, 0.6753246753246753, 0.6883116883116883, 0.7012987012987013, 0.6753246753246753, 0.6926406926406926, 0.7012987012987013, 0.6926406926406926, 0.6926406926406926, 0.683982683982684, 0.6926406926406926, 0.696969696969697, 0.6926406926406926]
Accuracy:  0.5974025974025974
Recall:  0.35365853658536583
Precision:  0.42028985507246375


In [99]:
X_train, X_test, y_train, y_test = train_test_split(X_norm,y, test_size=0.3)
scores =[]
for i in range(1,15):
  knn = KNeighborsClassifier(i)
  knn.fit(X_train,y_train)
  answers = knn.predict(X_test)
  scores.append(knn.score(X_test,y_test))
print(scores)

print("Accuracy: ", accuracy_score(y_test,y_pred))
print("Recall: ", recall_score(y_test,y_pred))
print("Precision: ", precision_score(y_test,y_pred))

[0.6796536796536796, 0.645021645021645, 0.7142857142857143, 0.7056277056277056, 0.7056277056277056, 0.7056277056277056, 0.7142857142857143, 0.7229437229437229, 0.7186147186147186, 0.70995670995671, 0.7142857142857143, 0.7229437229437229, 0.7359307359307359, 0.7316017316017316]
Accuracy:  0.5411255411255411
Recall:  0.2823529411764706
Precision:  0.34782608695652173


In [91]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()
model.fit(X_train, y_train)
ans_pred = model.predict(X_train)
print(model.score(X_test, y_test))

print("Accuracy: ", accuracy_score(y_test,y_pred))
print("Recall: ", recall_score(y_test,y_pred))
print("Precision: ", precision_score(y_test,y_pred))


0.7792207792207793
Accuracy:  0.5930735930735931
Recall:  0.345679012345679
Precision:  0.4057971014492754


Лучше всего было на стандартных данных