In [155]:
import pandas as pd
import numpy as np
from sklearn.cluster import KMeans
from sklearn.datasets import make_blobs
from sklearn import datasets
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.metrics import recall_score
from sklearn.metrics import precision_score
import scipy.cluster.hierarchy as sch
from sklearn.cluster import AgglomerativeClustering
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score, f1_score


In [2]:
from google.colab import files
uploaded = files.upload()

Saving diabetes.csv to diabetes.csv


In [127]:
df = pd.read_csv("diabetes.csv")
df


Pregnancies  Glucose  ...  Age  Outcome
0              6      148  ...   50        1
1              1       85  ...   31        0
2              8      183  ...   32        1
3              1       89  ...   21        0
4              0      137  ...   33        1
..           ...      ...  ...  ...      ...
763           10      101  ...   63        0
764            2      122  ...   27        0
765            5      121  ...   30        0
766            1      126  ...   47        1
767            1       93  ...   23        0

[768 rows x 9 columns]

In [128]:
y = df['Outcome']
x = df.drop(['Outcome'], axis = 1)

In [129]:
df.shape # размерность датафрэйма


(768, 9)

In [130]:
df.dtypes # какие типы данных в столбцах

Pregnancies                   int64
Glucose                       int64
BloodPressure                 int64
SkinThickness                 int64
Insulin                       int64
BMI                         float64
DiabetesPedigreeFunction    float64
Age                           int64
Outcome                       int64
dtype: object

In [131]:
df.isna().sum() # в каких стольбцах и сколько пропущенных значений

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [132]:
df['Outcome'].value_counts()

0    500
1    268
Name: Outcome, dtype: int64

In [133]:
#1
scaler = StandardScaler()
X_st = scaler.fit_transform(x)
X_st

array([[ 0.63994726,  0.84832379,  0.14964075, ...,  0.20401277,
         0.46849198,  1.4259954 ],
       [-0.84488505, -1.12339636, -0.16054575, ..., -0.68442195,
        -0.36506078, -0.19067191],
       [ 1.23388019,  1.94372388, -0.26394125, ..., -1.10325546,
         0.60439732, -0.10558415],
       ...,
       [ 0.3429808 ,  0.00330087,  0.14964075, ..., -0.73518964,
        -0.68519336, -0.27575966],
       [-0.84488505,  0.1597866 , -0.47073225, ..., -0.24020459,
        -0.37110101,  1.17073215],
       [-0.84488505, -0.8730192 ,  0.04624525, ..., -0.20212881,
        -0.47378505, -0.87137393]])

In [134]:
X_train, X_test, y_train, y_test = train_test_split(X_st, y, test_size=0.3, random_state=42)


In [135]:
scores = []
for i in range(1,15):
  knn = KNeighborsClassifier(i)
  knn.fit(X_train, y_train)
  answers = knn.predict(X_test) #метод predict возвращает вектор ответов для X_test

  scores.append(knn.score(X_test, y_test))

print(scores)

[0.6233766233766234, 0.670995670995671, 0.70995670995671, 0.6926406926406926, 0.6926406926406926, 0.6883116883116883, 0.7186147186147186, 0.683982683982684, 0.7012987012987013, 0.6926406926406926, 0.7012987012987013, 0.7142857142857143, 0.7142857142857143, 0.7186147186147186]


In [136]:
max_score = max(scores)
scores_ind = [i for i, v in enumerate(scores) if v == max_score]
scores_ind

[6, 13]

In [137]:
knn = KNeighborsClassifier(5)
# обучаем
knn.fit(X_train, y_train)
# предсказываем значения
y_pred = knn.predict(X_test)
# посмотрим матрицу ошибок
confusion_matrix(y_test, y_pred)

# 0 - общее 133+43
# 1 - общее 37+43

array([[119,  32],
       [ 39,  41]])

In [138]:
print("Accuracy:", accuracy_score(y_test, y_pred))
print("Recall:", recall_score(y_test, y_pred))
print("Precision:", precision_score(y_test, y_pred))


Accuracy: 0.6926406926406926
Recall: 0.5125
Precision: 0.5616438356164384


In [139]:
#2
scaler = MinMaxScaler()
X_st = scaler.fit_transform(x)
X_st

array([[0.35294118, 0.74371859, 0.59016393, ..., 0.50074516, 0.23441503,
        0.48333333],
       [0.05882353, 0.42713568, 0.54098361, ..., 0.39642325, 0.11656704,
        0.16666667],
       [0.47058824, 0.91959799, 0.52459016, ..., 0.34724292, 0.25362938,
        0.18333333],
       ...,
       [0.29411765, 0.6080402 , 0.59016393, ..., 0.390462  , 0.07130658,
        0.15      ],
       [0.05882353, 0.63316583, 0.49180328, ..., 0.4485842 , 0.11571307,
        0.43333333],
       [0.05882353, 0.46733668, 0.57377049, ..., 0.45305514, 0.10119556,
        0.03333333]])

In [140]:
X_train, X_test, y_train, y_test = train_test_split(X_st, y, test_size=0.3, random_state=42)

In [141]:
scores = []
for i in range(1,15):
  knn = KNeighborsClassifier(i)
  knn.fit(X_train, y_train)
  answers = knn.predict(X_test) #метод predict возвращает вектор ответов для X_test

  scores.append(knn.score(X_test, y_test))

print(scores)

[0.6753246753246753, 0.6796536796536796, 0.6926406926406926, 0.696969696969697, 0.6796536796536796, 0.6666666666666666, 0.7142857142857143, 0.696969696969697, 0.7229437229437229, 0.7056277056277056, 0.7012987012987013, 0.6883116883116883, 0.6926406926406926, 0.6883116883116883]


In [142]:
max_score = max(scores)
scores_ind = [i for i, v in enumerate(scores) if v == max_score]
scores_ind
knn = KNeighborsClassifier(5)
# обучаем
knn.fit(X_train, y_train)
# предсказываем значения
y_pred = knn.predict(X_test)
# посмотрим матрицу ошибок
confusion_matrix(y_test, y_pred)

# 0 - общее 133+43
# 1 - общее 37+43

array([[118,  33],
       [ 41,  39]])

In [143]:
print("Accuracy:", accuracy_score(y_test, y_pred))
print("Recall:", recall_score(y_test, y_pred))
print("Precision:", precision_score(y_test, y_pred))

Accuracy: 0.6796536796536796
Recall: 0.4875
Precision: 0.5416666666666666


In [ ]:
# Стандартизированные в knn лучше чем нормализованные данные по всем показателям 

In [156]:
#3
scaler = StandardScaler()
X_st = scaler.fit_transform(x)
X_st

array([[ 0.63994726,  0.84832379,  0.14964075, ...,  0.20401277,
         0.46849198,  1.4259954 ],
       [-0.84488505, -1.12339636, -0.16054575, ..., -0.68442195,
        -0.36506078, -0.19067191],
       [ 1.23388019,  1.94372388, -0.26394125, ..., -1.10325546,
         0.60439732, -0.10558415],
       ...,
       [ 0.3429808 ,  0.00330087,  0.14964075, ..., -0.73518964,
        -0.68519336, -0.27575966],
       [-0.84488505,  0.1597866 , -0.47073225, ..., -0.24020459,
        -0.37110101,  1.17073215],
       [-0.84488505, -0.8730192 ,  0.04624525, ..., -0.20212881,
        -0.47378505, -0.87137393]])

In [158]:
X_train, X_test, y_train, y_test = train_test_split(x,y, test_size=0.3)
#обучаем модель 
model = LogisticRegression()
model.fit(X_train, y_train)
otvets_pred = model.predict(X_test)
#оцениваем
print(accuracy_score(y_test, otvets_pred))
print(recall_score(y_test, otvets_pred))
print(precision_score(y_test, otvets_pred))

0.7792207792207793
0.5862068965517241
0.7727272727272727


/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


In [159]:
#4
scaler = MinMaxScaler()
X_st = scaler.fit_transform(x)
X_st

array([[0.35294118, 0.74371859, 0.59016393, ..., 0.50074516, 0.23441503,
        0.48333333],
       [0.05882353, 0.42713568, 0.54098361, ..., 0.39642325, 0.11656704,
        0.16666667],
       [0.47058824, 0.91959799, 0.52459016, ..., 0.34724292, 0.25362938,
        0.18333333],
       ...,
       [0.29411765, 0.6080402 , 0.59016393, ..., 0.390462  , 0.07130658,
        0.15      ],
       [0.05882353, 0.63316583, 0.49180328, ..., 0.4485842 , 0.11571307,
        0.43333333],
       [0.05882353, 0.46733668, 0.57377049, ..., 0.45305514, 0.10119556,
        0.03333333]])

In [160]:
X_train, X_test, y_train, y_test = train_test_split(x,y, test_size=0.3)
#обучаем модель 
model = LogisticRegression()
model.fit(X_train, y_train)
otvets_pred = model.predict(X_test)
#оцениваем
print(accuracy_score(y_test, otvets_pred))
print(recall_score(y_test, otvets_pred))
print(precision_score(y_test, otvets_pred))

0.7575757575757576
0.5897435897435898
0.6571428571428571


/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


In [ ]:
# Логистическая стандартизированная также лучше логистической нормализованной

In [ ]:
# В итоге логистические регрессии выходят более точные чем kknы