In [11]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split

In [1]:
from google.colab import files 
uploaded = files.upload()

Saving diabetes.csv to diabetes.csv


In [3]:
df = pd.read_csv("diabetes.csv")
df

Pregnancies  Glucose  ...  Age  Outcome
0              6      148  ...   50        1
1              1       85  ...   31        0
2              8      183  ...   32        1
3              1       89  ...   21        0
4              0      137  ...   33        1
..           ...      ...  ...  ...      ...
763           10      101  ...   63        0
764            2      122  ...   27        0
765            5      121  ...   30        0
766            1      126  ...   47        1
767            1       93  ...   23        0

[768 rows x 9 columns]

In [4]:
print(df.shape)

(768, 9)


In [5]:
print(df.isna().sum())

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64


In [6]:
print(df['Outcome'].value_counts())

0    500
1    268
Name: Outcome, dtype: int64


In [8]:
X =  df.drop(['Outcome'], axis = 1)
y = df['Outcome']

In [9]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_st = scaler.fit_transform(X)
X_st



array([[ 0.63994726,  0.84832379,  0.14964075, ...,  0.20401277,
         0.46849198,  1.4259954 ],
       [-0.84488505, -1.12339636, -0.16054575, ..., -0.68442195,
        -0.36506078, -0.19067191],
       [ 1.23388019,  1.94372388, -0.26394125, ..., -1.10325546,
         0.60439732, -0.10558415],
       ...,
       [ 0.3429808 ,  0.00330087,  0.14964075, ..., -0.73518964,
        -0.68519336, -0.27575966],
       [-0.84488505,  0.1597866 , -0.47073225, ..., -0.24020459,
        -0.37110101,  1.17073215],
       [-0.84488505, -0.8730192 ,  0.04624525, ..., -0.20212881,
        -0.47378505, -0.87137393]])

In [10]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
X_norm = scaler.fit_transform(X)
X_norm

array([[0.35294118, 0.74371859, 0.59016393, ..., 0.50074516, 0.23441503,
        0.48333333],
       [0.05882353, 0.42713568, 0.54098361, ..., 0.39642325, 0.11656704,
        0.16666667],
       [0.47058824, 0.91959799, 0.52459016, ..., 0.34724292, 0.25362938,
        0.18333333],
       ...,
       [0.29411765, 0.6080402 , 0.59016393, ..., 0.390462  , 0.07130658,
        0.15      ],
       [0.05882353, 0.63316583, 0.49180328, ..., 0.4485842 , 0.11571307,
        0.43333333],
       [0.05882353, 0.46733668, 0.57377049, ..., 0.45305514, 0.10119556,
        0.03333333]])

In [12]:

# метод соседей для стандартизированных данных
X_train, X_test, y_train, y_test = train_test_split(X_st, y, test_size=0.3, random_state = 42)



In [15]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix

scores = []
for i in range(1,15):

  knn = KNeighborsClassifier(i)
  knn.fit(X_train, y_train)
  answers = knn.predict(X_test)

  scores.append(knn.score(X_test, y_test))

print(scores)

  

[0.6233766233766234, 0.670995670995671, 0.70995670995671, 0.6926406926406926, 0.6926406926406926, 0.6883116883116883, 0.7186147186147186, 0.683982683982684, 0.7012987012987013, 0.6926406926406926, 0.7012987012987013, 0.7142857142857143, 0.7142857142857143, 0.7186147186147186]


In [16]:
max_score = max(scores)
scores_ind = [i for i, v in enumerate(scores) if v == max_score]
scores_ind

[6, 13]

In [21]:
knn = KNeighborsClassifier(5)

knn.fit(X_train, y_train)

y_pred = knn.predict(X_test)

confusion_matrix(y_test, y_pred)

array([[119,  32],
       [ 39,  41]])

In [22]:
from sklearn.metrics import accuracy_score
from sklearn.metrics import recall_score
from sklearn.metrics import precision_score

print("Accuracy" , accuracy_score(y_test, y_pred))
print("Recall" ,recall_score(y_test, y_pred))
print("Precision" , precision_score(y_test, y_pred)) #для стандартизированных данных

Accuracy 0.6926406926406926
Recall 0.5125
Precision 0.5616438356164384


In [24]:
#метод соседей для нормализованных данных

X_train, X_test, y_train, y_test = train_test_split(X_norm, y, test_size=0.3, random_state = 42)

In [25]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix

scores = []
for i in range(1,15):

  knn = KNeighborsClassifier(i)
  knn.fit(X_train, y_train)
  answers = knn.predict(X_test)

  scores.append(knn.score(X_test, y_test))

print(scores)

[0.6753246753246753, 0.6796536796536796, 0.6926406926406926, 0.696969696969697, 0.6796536796536796, 0.6666666666666666, 0.7142857142857143, 0.696969696969697, 0.7229437229437229, 0.7056277056277056, 0.7012987012987013, 0.6883116883116883, 0.6926406926406926, 0.6883116883116883]


In [26]:
max_score = max(scores)
scores_ind = [i for i, v in enumerate(scores) if v == max_score]
scores_ind

[8]

In [30]:
knn = KNeighborsClassifier(7)

knn.fit(X_train, y_train)

y_pred = knn.predict(X_test)

confusion_matrix(y_test, y_pred)

array([[126,  24],
       [ 44,  37]])

In [31]:
from sklearn.metrics import accuracy_score
from sklearn.metrics import recall_score
from sklearn.metrics import precision_score

print("Accuracy" , accuracy_score(y_test, y_pred))
print("Recall" ,recall_score(y_test, y_pred))
print("Precision" , precision_score(y_test, y_pred)) #для нормализованных данных

Accuracy 0.7056277056277056
Recall 0.4567901234567901
Precision 0.6065573770491803


In [37]:
#логистическая регрессия для стандартизированных данных

X_train, X_test, y_train, y_test = train_test_split(X_st,y, test_size=0.3, random_state = 42)
model = LogisticRegression()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)

print("Accuracy" , accuracy_score(y_test, y_pred))
print("Recall" ,recall_score(y_test, y_pred))
print("Precision" , precision_score(y_test, y_pred)) 
confusion_matrix(y_test, y_pred)

Accuracy 0.7359307359307359
Recall 0.625
Precision 0.6172839506172839


array([[120,  31],
       [ 30,  50]])

In [38]:
#логистическая регрессия для нормализованных данных

X_train, X_test, y_train, y_test = train_test_split(X_norm,y, test_size=0.3, random_state = 42)
model = LogisticRegression()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)

print("Accuracy" , accuracy_score(y_test, y_pred))
print("Recall" ,recall_score(y_test, y_pred))
print("Precision" , precision_score(y_test, y_pred)) 
confusion_matrix(y_test, y_pred)

Accuracy 0.7445887445887446
Recall 0.5625
Precision 0.6521739130434783


array([[127,  24],
       [ 35,  45]])

In [ ]:
#на мой взгляд наилучшую оценку показала логистическая регрессия для нормализованных данных, так как оценка качества модели у нее лучше остальных.